"""App Factory - the validated data contracts.

Three modules, one import surface:

  common.py    enums, identifier patterns, Issue, Telemetry, RubricScores,
               and the fingerprint contract that defines defect identity
  state.py     ProjectState - project_state.json, the master bus - plus the
               G8 write-ACL maps
  envelope.py  EnvelopeBase, the seven per-agent payloads, and the
               discriminated union that routes a reply to its schema

common.py exists as a separate module because Issue is the one model both the
bus and the envelope need; splitting it avoids a circular import.
"""

from __future__ import annotations

from .common import (
    BLOCKING_SEVERITIES,
    COMMON_SUFFIXES,
    PRECEDENCE_ORDER,
    RUBRIC_INTERPRETATION,
    SCHEMA_VERSION,
    SEVERITY_RANK,
    STACK_PROFILES,
    AcId,
    AgentRole,
    Ambiguity,
    BuildId,
    ContextAction,
    Fingerprint,
    GateDecision,
    Issue,
    IssueCategory,
    IssueId,
    IssueState,
    OutputStatus,
    PipelineStatus,
    PreviewMode,
    Priority,
    ProjectSlug,
    ProjectType,
    ReqId,
    RubricScores,
    RuleId,
    RunId,
    ScopeVerdict,
    Severity,
    Sha256,
    SnapshotId,
    Stack,
    StackProfile,
    Stage,
    StateHash,
    Strict,
    Telemetry,
    compute_fingerprint,
    normalize_evidence,
    profile_for,
    utcnow,
)
from .envelope import (
    PAYLOAD_SCHEMAS,
    AgentOutput,
    AgentOutputAdapter,
    Assumption,
    CliResponse,
    CommanderOutput,
    CommanderPayload,
    DesignOutput,
    DesignPayload,
    EnvelopeBase,
    ImplementerOutput,
    ImplementerPayload,
    ObserverAdjudicationPayload,
    ObserverContextSavePayload,
    ObserverOutput,
    ObserverPayload,
    ObserverSpecPayload,
    OptimizerOutput,
    OptimizerPayload,
    PromptEngineerOutput,
    PromptEngineerPayload,
    QcOutput,
    QcPayload,
    ReasonCode,
    Request,
    RuleDraft,
    StateHashRef,
    StepId,
)
from .registry import (
    PROJECTS_DIRNAME,
    REGISTRY_FILENAME,
    ProjectRecord,
    ProjectRegistry,
    ProjectStatus,
    default_runs_dir,
)
from .state import (
    OWNED_REGIONS,
    STATE_MANAGER_REGIONS,
    AcceptanceCriterion,
    Architecture,
    ArtifactFile,
    Artifacts,
    Budgets,
    Component,
    ContextActionRecord,
    CriticResult,
    Dependency,
    Deviation,
    FilePlan,
    Intent,
    Memory,
    Meta,
    Pipeline,
    ProjectState,
    Requirement,
    Review,
    Rule,
    RuleSet,
    Spec,
    StageTransition,
)

__all__ = [
    # common - constants
    "SCHEMA_VERSION",
    "SEVERITY_RANK",
    "BLOCKING_SEVERITIES",
    "PRECEDENCE_ORDER",
    "COMMON_SUFFIXES",
    "STACK_PROFILES",
    "RUBRIC_INTERPRETATION",
    # common - enums
    "AgentRole",
    "Stage",
    "PipelineStatus",
    "Severity",
    "IssueCategory",
    "IssueState",
    "OutputStatus",
    "ContextAction",
    "GateDecision",
    "Priority",
    "Stack",
    "ProjectType",
    "PreviewMode",
    # common - identifiers
    "ReqId",
    "AcId",
    "IssueId",
    "RuleId",
    "RunId",
    "BuildId",
    "SnapshotId",
    "Fingerprint",
    "Sha256",
    "StateHash",
    "ProjectSlug",
    # common - models and helpers
    "Strict",
    "Telemetry",
    "Issue",
    "Ambiguity",
    "ScopeVerdict",
    "RubricScores",
    "normalize_evidence",
    "compute_fingerprint",
    "utcnow",
    "StackProfile",
    "profile_for",
    # state - the bus
    "Meta",
    "StageTransition",
    "Pipeline",
    "Intent",
    "Requirement",
    "AcceptanceCriterion",
    "Spec",
    "Component",
    "FilePlan",
    "Dependency",
    "Deviation",
    "Architecture",
    "ArtifactFile",
    "Artifacts",
    "CriticResult",
    "Review",
    "Rule",
    "RuleSet",
    "Budgets",
    "ContextActionRecord",
    "Memory",
    "ProjectState",
    "OWNED_REGIONS",
    "STATE_MANAGER_REGIONS",
    # envelope
    "StepId",
    "StateHashRef",
    "CliResponse",
    "ReasonCode",
    "Request",
    "Assumption",
    "EnvelopeBase",
    "OptimizerPayload",
    "ObserverSpecPayload",
    "ObserverAdjudicationPayload",
    "ObserverContextSavePayload",
    "ObserverPayload",
    "ImplementerPayload",
    "QcPayload",
    "DesignPayload",
    "RuleDraft",
    "PromptEngineerPayload",
    "CommanderPayload",
    "OptimizerOutput",
    "ObserverOutput",
    "ImplementerOutput",
    "QcOutput",
    "DesignOutput",
    "PromptEngineerOutput",
    "CommanderOutput",
    "AgentOutput",
    "AgentOutputAdapter",
    "PAYLOAD_SCHEMAS",
    # registry - saved-project-context.json
    "ProjectRecord",
    "ProjectRegistry",
    "ProjectStatus",
    "REGISTRY_FILENAME",
    "PROJECTS_DIRNAME",
    "default_runs_dir",
]
